def jenkins = library(identifier: "t@master", retriever: legacySCM(scm)).jenkins

pipeline {
    agent none
    stages {
        stage('notify') {
            agent {
                docker {
                    label 'Jenkins-Agent-Ubuntu2004-X64-m52xlarge-Docker-Builder'
                    image 'opensearchstaging/ci-runner:ubuntu2004-x64-docker-buildx0.6.3-qemu5.0'
                    args '-u root -v /var/run/docker.sock:/var/run/docker.sock'
                    alwaysPull true
                }
            }
            steps {
                script { 
                    echo "Pushing messages ..."
                    def messages = jenkins.Messages.new(this) 
                    messages.add("${STAGE_NAME}-1", "Test 1")
                    messages.add("${STAGE_NAME}-2", "Test 2")
                    echo "Gathering messages ..."
                    all = messages.all(["notify-1", "notify-2"])
                    echo "All messages:\n${all}"
                    messages.add("${STAGE_NAME}-3", "Updated")
                    all = messages.all(["notify-3"])
                    echo "All messages:\n${all}"
                }
            }
        }
    }
}
