library identifier: 'loadLocalLibrary@refactor-jenkinsfile', retriever: legacySCM(scm)

pipeline {
    agent none
    stages {
        stage('notify') {
            agent {
                docker {
                    label 'Jenkins-Agent-Ubuntu2004-X64-m52xlarge-Docker-Builder'
                    image 'opensearchstaging/ci-runner:ubuntu2004-x64-docker-buildx0.6.3-qemu5.0'
                    args '-u root -v /var/run/docker.sock:/var/run/docker.sock'
                    alwaysPull true
                }
            }
            steps {
                script { 
                    echo "Running step ..."
                    notifySlack()
                }
            }
        }
    }
}
