library identifier: 'addJenkinsMessage@refactor-jenkinsfile', retriever: legacySCM(scm)
library identifier: 'getJenkinsMessages@refactor-jenkinsfile', retriever: legacySCM(scm)

pipeline {
    agent none
    stages {
        stage('notify') {
            agent {
                docker {
                    label 'Jenkins-Agent-Ubuntu2004-X64-m52xlarge-Docker-Builder'
                    image 'opensearchstaging/ci-runner:ubuntu2004-x64-docker-buildx0.6.3-qemu5.0'
                    args '-u root -v /var/run/docker.sock:/var/run/docker.sock'
                    alwaysPull true
                }
            }
            steps {
                script { 
                    echo "Pushing messages ..."
                    addJenkinsMessage("${STAGE_NAME}-1", "Test 1")
                    addJenkinsMessage("${STAGE_NAME}-2", "Test 2")
                    echo "Gathering messages ..."
                    messages = getJenkinsMessages(["notify-1", "notify-2"])
                    echo "All messages:\n${messages}"
                }
            }
        }
    }
}
